//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DemoShapeDBEntities : DbContext
    {
        public DemoShapeDBEntities()
            : base("name=DemoShapeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<ShapeType> ShapeTypes { get; set; }
        public virtual DbSet<ShapesArea> ShapesAreas { get; set; }
    
        public virtual ObjectResult<GetShapeByID_Result> GetShapeByID(Nullable<int> shapeid)
        {
            var shapeidParameter = shapeid.HasValue ?
                new ObjectParameter("shapeid", shapeid) :
                new ObjectParameter("shapeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetShapeByID_Result>("GetShapeByID", shapeidParameter);
        }
    
        public virtual ObjectResult<GetShapeByType_Result> GetShapeByType(string shapetype)
        {
            var shapetypeParameter = shapetype != null ?
                new ObjectParameter("shapetype", shapetype) :
                new ObjectParameter("shapetype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetShapeByType_Result>("GetShapeByType", shapetypeParameter);
        }
    }
}
