//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shape
    {
        public int pk { get; set; }
        public int height { get; set; }
        public int width { get; set; }
        public int fk_ShapeType { get; set; }
    
        public virtual ShapeType ShapeType { get; set; }
    }
}
